---
# Based on: 
#   https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis
#   https://github.com/drhelius/travis-ansible-demo
#   https://www.jeffgeerling.com/blog/2018/how-i-test-ansible-configuration-on-7-different-oses-docker 

notifications:
  email: false

sudo: required

env:
  - distribution: ubuntu
    version: bionic
    ansible_extra_vars: "'mysql_version_major=5 mysql_version_minor=7'"
  - distribution: ubuntu
    version: xenial
    ansible_extra_vars: "ansible_python_interpreter=/usr/bin/python3"
  - distribution: ubuntu
    version: xenial
    ansible_extra_vars: ""
  - distribution: ubuntu
    version: trusty
    ansible_extra_vars: ""
  - distribution: centos
    version: 7
    ansible_extra_vars: ""
  - distribution: ubuntu
    version: xenial
    ansible_extra_vars: "'mysql_version_major=5 mysql_version_minor=7'"
  - distribution: centos
    version: 7
    ansible_extra_vars: "'mysql_version_major=5 mysql_version_minor=7'"


services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v --extra-vars "${ansible_extra_vars}" /etc/ansible/roles/role_under_test/travis/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v --extra-vars "${ansible_extra_vars}" /etc/ansible/roles/role_under_test/travis/test.yml'

  ## skipping idempotence tests for now
  # - >
  #   sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/clamav_role/travis/test.yml
  #   | grep -q 'changed=0.*failed=0'
  #   && (echo 'Idempotence test: pass' && exit 0)
  #   || (echo 'Idempotence test: fail' && exit 1)

  # Check to make sure we can connect to MySQL as root via Unix socket.
  - >
    sudo docker exec "$(cat ${container_id})" mysql -u root -e 'show databases;'
    | grep -q 'information_schema'
    && (echo 'OK: Able to login to MySQL server as root' && exit 0)
    || (echo 'Error: Unable to login to MySQL server as root' && exit 1)

  # Check to make sure we can connect to MySQL as root via TCP.
  - >
    sudo docker exec "$(cat ${container_id})" mysql -h 127.0.0.1 -u root -e 'show databases;'
    | grep -q 'information_schema'
    && (echo 'OK: Able to login to MySQL server as root' && exit 0)
    || (echo 'Error: Unable to login to MySQL server as root' && exit 1)


  - 'sudo docker rm -f "$(cat ${container_id})"'