---
- name: "Add Percona yum repository"
  yum:
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    state: present

- name: "Install percona database server"
  yum:
    name: "{{Â item }}"
    state: present
  with_items:
    - "Percona-Server-server-{{mysql_version_major}}{{mysql_version_minor}}"
    - "Percona-Server-client-{{mysql_version_major}}{{mysql_version_minor}}"
    - "Percona-Server-devel-{{mysql_version_major}}{{mysql_version_minor}}"
    - "percona-toolkit"
    - "percona-xtrabackup"

- name: "Install MySQL-python package"
  yum:
    name: "MySQL-python"
    state: present

- name: "Adjust permissions of datadir"
  file:
    path: "{{ mysql_datadir }}"
    owner: "mysql"
    group: "mysql"
    mode: 0755
    state: "directory"

- name: "Ensure that percona is running and enabled"
  service:
    name: "mysql"
    state: "started"
    enabled: "yes"
